#!/bin/sh

set -e

echo ""
echo "[BUILD]:"
echo ""
make "ASANFLAGS+=-fsanitize=address -fsanitize=leak -fsanitize=undefined"  "${1}"

echo ""
echo "[OUTPUT]:"
echo ""
MallocNanoZone=0 ./run "${1}"
echo ""
